version: "3"
services:
  app:
    container_name: qr-Generator
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: suhailtaj/qr-generator:latest
    ports:
      - "80:3000"
